vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        pops:
            uri_prefix: /images/pops
            upload_destination: '%kernel.project_dir%/public/images/pops'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        stickers:
            uri_prefix: /images/stickers
            upload_destination: '%kernel.project_dir%/public/images/stickers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
