services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: popentin_php
    volumes:
      - .:/var/www/html
    networks:
      - popentin
    depends_on:
      - database
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER:-popentin}:${MYSQL_PASSWORD:-popentin123}@database:3306/${MYSQL_DATABASE:-popentin}?serverVersion=8.0&charset=utf8mb4"
      APP_ENV: ${APP_ENV:-dev}
      APP_SECRET: ${APP_SECRET:-30f9147a676904f4edcd8893dc2b91b5}

  nginx:
    image: nginx:alpine
    container_name: popentin_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - popentin
    depends_on:
      - php

###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-8.0}
    container_name: popentin_database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-popentin}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-popentin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-popentin123}
    volumes:
      - database_data:/var/lib/mysql:rw
    networks:
      - popentin
###< doctrine/doctrine-bundle ###

networks:
  popentin:
    driver: bridge

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
